DROP TABLE IF EXISTS CUSTOMERTRANSACTIONS;
 
CREATE TABLE CUSTOMERTRANSACTIONS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  customerName VARCHAR(250) NOT NULL,
  itemDescription VARCHAR(250) NOT NULL,
  purchasePrice INT NOT NULL,
  purchaseDate DATE NOT NULL
);
